# Generated by Django 5.1.2 on 2024-12-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id_assistance', models.AutoField(primary_key=True, serialize=False)),
                ('date_assistance', models.DateField()),
                ('time_assistance', models.TimeField()),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
    ]
