# Generated by Django 5.1.2 on 2024-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_unique', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('register', models.BinaryField(null=True)),
                ('rol', models.CharField(choices=[('ST', 'Student'), ('PR', 'Professor'), ('MO', 'Monitor')], default='ST', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='user.user')),
            ],
        ),
    ]
