# Generated by Django 5.1.2 on 2024-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('id_answer', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
