# Generated by Django 5.1.2 on 2024-12-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('question', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='correct_option',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='options',
            name='id_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
        migrations.AddField(
            model_name='options',
            name='id_unique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='options',
            name='option',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='options',
            name='id_answer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='student_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.options')),
                ('id_unique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
