# Generated by Django 5.1.2 on 2024-11-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id_question', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
